### ISSUE TITLE
get_metalab_data doesn't retrieve all data

### ISSUE THREAD

**Issue by mllewis** [langcog/metalabr#4]
`ml_data <- get_metalab_data(ml_dataset_info)` reports an error for the short_cite field for a handful of dataset when downloading data (`Dataset Statistical word segmentation has length greater than limit (35 characters) in 'short_cite'`). For datasets with this error, the data does not get read in. There are currently 6 such datasets for the early language learning domain.

**Comment by erikriverson** [comment]
@mllewis Sara is looking into this, she will push up a fix shortly. Thank you for the report!

**Comment by saraelshawa** [comment]
@mllewis I've changed the character limit to 60 for short_cite field, let me know if you have any other issues!

**Comment by mllewis** [comment]
Thanks, Sara!

**Comment by mllewis** [comment]
Looks like two MAs are still excluded with the 60 character limit, Sound symbolism  and Switch Task. Is there a reason to have a character limit at all? Or perhaps this should be validated when the data are initially read into metalab?

**Comment by christinabergmann** [comment]
Hi @mllewis, the character limit is so the forest plot doesn't break, it was a soft requirement that was broken by many entries, so I thought it should be a hard requirement. Maybe it's worthwhile checking all datasets and then we shouldn't see this issue any more?

**Comment by mllewis** [comment]
@christinabergmann - It looks like these two MAs are on the website, but are not included in the package. I can see why the character limit is important for plotting functionality, but it shouldn't matter for inclusion in the package. I'm not sure why this is problem for the package but not validation for the website...

**Comment by erikriverson** [comment]
@mllewis I see what you're saying now. The website uses a specific version of every package it depends on, including the metalabr package. I believe the version of metalabr the website currently depends on is the one before this most recent change with checking the short_cite length. The next time we push an update to the site, we will bump the version dependency of metalabr so they are in sync. 

In general, changes to the package would likely result in us bumping the version of the metalabr dependency and re-deploying immediately. That will be a practice I will put in place, so this should happen less after the current bit of work is done.

**Comment by mllewis** [comment]
Thanks, @erikriverson - that makes sense. I fixed the offending rows in the Switch and Symbolism spreadsheets. So everything should validate now (at least for language learning domain).

**Comment by saraelshawa** [comment]
@mllewis sorry, hadn't noticed that you were using a different version of metalabr!
